# permissions for end users to view customissuers.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: customissuer-viewer-role
rules:
- apiGroups:
  - cert-manager.k8s.sakamo.dev
  resources:
  - customissuers
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - cert-manager.k8s.sakamo.dev
  resources:
  - customissuers/status
  verbs:
  - get
