# permissions for end users to edit customissuers.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: customissuer-editor-role
rules:
- apiGroups:
  - cert-manager.k8s.sakamo.dev
  resources:
  - customissuers
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - cert-manager.k8s.sakamo.dev
  resources:
  - customissuers/status
  verbs:
  - get
