apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: example-certificate
spec:
  secretName: example-com-tls
  dnsNames:
  - example.com
  - www.example.com
  duration: 2160h
  renewBefore: 720h
  issuerRef:
    group: cert-manager.k8s.sakamo.dev
    kind: CustomIssuer
    name: customissuer-sample
